import type { PaperMagicAppGroup, PaperMagicModule } from './types';

export const PAPER_MAGIC_MODULES: PaperMagicModule[] = [
  {
    id: 'memory-persona',
    title: '记忆与人设工坊',
    subtitle: '压缩历史、抽取角色档案与世界书',
    icon: 'Brain',
    promptIds: [
      'memory.summary.compress',
      'persona.extract.profile',
      'persona.extract.system',
      'persona.skill.intakeBasicInfo',
      'persona.skill.memoriesGeneration',
      'persona.skill.personalityGeneration',
      'settings.vision.probe',
    ],
  },
  {
    id: 'social-bonds',
    title: '社交与陪伴',
    subtitle: '微信聊天、朋友圈与关系时间线',
    icon: 'MessagesSquare',
    promptIds: [
      'lovespace.importantTimeline.extract',
      'wechat.moments.generateDrafts',
      'wechat.moments.fallbackImage',
      'wechat.moments.imageProbe',
      'wechat.chat.characterSystem',
      'wechat.chat.context.worldBook',
      'wechat.chat.context.memory',
      'wechat.chat.context.personalProfile',
      'wechat.chat.context.sessionIntro',
      'wechat.chat.context.latestTurn',
      'wechat.chat.specialMessage.image',
      'wechat.chat.specialMessage.order',
      'wechat.chat.specialMessage.movieTicket',
      'wechat.chat.specialMessage.gift',
      'wechat.chat.specialMessage.recipe',
      'wechat.chat.specialMessage.listenInvite',
      'wechat.chat.specialMessage.listenSummary',
      'wechat.chat.specialMessage.transfer',
      'wechat.chat.specialMessage.transferAccepted',
      'wechat.chat.orderRequestDecision',
      'wechat.chat.listenTogetherDecision',
      'wechat.chat.movieTicketDecision',
      'wechat.chat.giftDecision',
      'wechat.chat.recipeDecision',
      'wechat.chat.imageDecision',
      'wechat.chat.transferDecision',
      'wechat.voice.ttsPayload',
    ],
  },
  {
    id: 'commerce-life',
    title: '商业与生活',
    subtitle: '开店、交易、购物陪伴与私厨菜谱',
    icon: 'ShoppingBag',
    promptIds: [
      'commerce.buyerInquiry',
      'commerce.orderFailedRetry',
      'seller.productDrafts',
      'seller.productImageFallback.movie',
      'seller.productImageFallback.flower',
      'seller.productImageFallback.dessert',
      'seller.buyerAutoReply',
      'shopping.companionReply',
      'delivery.kitchenRecipes',
    ],
  },
  {
    id: 'entertainment',
    title: '娱乐剧本',
    subtitle: '每日计划、音乐评论与轻量创作',
    icon: 'Clapperboard',
    promptIds: [
      'dailyscript.planBuilder',
      'dreammusic.commentTrack',
    ],
  },
];

export const PAPER_MAGIC_APP_GROUPS: PaperMagicAppGroup[] = [
  {
    id: 'memory-center',
    moduleId: 'memory-persona',
    title: '记忆中心',
    subtitle: '历史记录压缩与长期记忆沉淀',
    promptIds: ['memory.summary.compress'],
  },
  {
    id: 'persona-generator',
    moduleId: 'memory-persona',
    title: '人设生成器',
    subtitle: '角色档案、世界书与 Skill 模板',
    promptIds: [
      'persona.extract.profile',
      'persona.extract.system',
      'persona.skill.intakeBasicInfo',
      'persona.skill.memoriesGeneration',
      'persona.skill.personalityGeneration',
    ],
  },
  {
    id: 'settings-ai',
    moduleId: 'memory-persona',
    title: '设置',
    subtitle: '模型视觉能力检测',
    promptIds: ['settings.vision.probe'],
  },
  {
    id: 'wechat',
    moduleId: 'social-bonds',
    title: '微信',
    subtitle: '聊天、朋友圈、图片、转账和语音上下文',
    promptIds: [
      'wechat.moments.generateDrafts',
      'wechat.moments.fallbackImage',
      'wechat.moments.imageProbe',
      'wechat.chat.characterSystem',
      'wechat.chat.context.worldBook',
      'wechat.chat.context.memory',
      'wechat.chat.context.personalProfile',
      'wechat.chat.context.sessionIntro',
      'wechat.chat.context.latestTurn',
      'wechat.chat.specialMessage.image',
      'wechat.chat.specialMessage.order',
      'wechat.chat.specialMessage.movieTicket',
      'wechat.chat.specialMessage.gift',
      'wechat.chat.specialMessage.recipe',
      'wechat.chat.specialMessage.listenInvite',
      'wechat.chat.specialMessage.listenSummary',
      'wechat.chat.specialMessage.transfer',
      'wechat.chat.specialMessage.transferAccepted',
      'wechat.chat.orderRequestDecision',
      'wechat.chat.listenTogetherDecision',
      'wechat.chat.movieTicketDecision',
      'wechat.chat.giftDecision',
      'wechat.chat.recipeDecision',
      'wechat.chat.imageDecision',
      'wechat.chat.transferDecision',
      'wechat.voice.ttsPayload',
    ],
  },
  {
    id: 'lovespace',
    moduleId: 'social-bonds',
    title: '恋爱空间',
    subtitle: '关系时间线重要事件提取',
    promptIds: ['lovespace.importantTimeline.extract'],
  },
  {
    id: 'commerce-bridge',
    moduleId: 'commerce-life',
    title: '商业消息桥',
    subtitle: '买家咨询与下单失败追问',
    promptIds: ['commerce.buyerInquiry', 'commerce.orderFailedRetry'],
  },
  {
    id: 'seller',
    moduleId: 'commerce-life',
    title: '开店吧',
    subtitle: '商品生成、主图提示词与买家自动回复',
    promptIds: [
      'seller.productDrafts',
      'seller.productImageFallback.movie',
      'seller.productImageFallback.flower',
      'seller.productImageFallback.dessert',
      'seller.buyerAutoReply',
    ],
  },
  {
    id: 'shopping',
    moduleId: 'commerce-life',
    title: '购物',
    subtitle: '一起购物陪伴搭子回复',
    promptIds: ['shopping.companionReply'],
  },
  {
    id: 'delivery',
    moduleId: 'commerce-life',
    title: '外卖',
    subtitle: '私家厨房菜谱生成',
    promptIds: ['delivery.kitchenRecipes'],
  },
  {
    id: 'dailyscript',
    moduleId: 'entertainment',
    title: '每日剧本',
    subtitle: '自然语言计划转自动化剧本',
    promptIds: ['dailyscript.planBuilder'],
  },
  {
    id: 'dreammusic',
    moduleId: 'entertainment',
    title: '梦音乐',
    subtitle: '歌曲评论自动生成',
    promptIds: ['dreammusic.commentTrack'],
  },
];
