import type { PaperMagicPrompt } from '../types';
import { definePaperMagicPrompt } from './definePaperMagicPrompt';

export const WECHAT_PROMPTS: PaperMagicPrompt[] = [
  definePaperMagicPrompt({
    id: 'wechat.moments.generateDrafts',
    moduleId: 'social-bonds',
    title: '微信朋友圈：文案生成',
    source: 'src/appsrc/apps/WeChat/components/moments/momentsAiService.ts',
    kind: 'chat',
    description: '生成朋友圈动态草稿及图片提示词。',
    system: '你是微信朋友圈文案生成器。只输出 JSON，不要任何解释。',
    user: '请生成 ${count} 条朋友圈动态，作者只能从以下作者中选择：${authorPayloadJson}。返回 JSON 数组，每个元素结构为：{"authorId":"作者ID","content":"文案","imagePrompt":"图片提示词"}。\n要求：\n1) content 为自然中文，15-45字。\n2) authorId 必须来自给定作者。\n3) ${imageInstruction}\n4) 只返回 JSON 数组。',
    variables: ['count', 'authorPayloadJson', 'imageInstruction'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.moments.fallbackImage',
    moduleId: 'social-bonds',
    title: '微信朋友圈：兜底图片提示词',
    source: 'src/appsrc/apps/WeChat/components/moments/momentsAiService.ts',
    kind: 'image',
    description: '朋友圈草稿未返回 imagePrompt 时使用的图片生成提示词。',
    content: '${authorName} 的微信朋友圈配图，生活感，内容：${content}',
    variables: ['authorName', 'content'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.moments.imageProbe',
    moduleId: 'social-bonds',
    title: '微信：朋友圈图片能力探测',
    source: 'src/appsrc/apps/WeChat/components/WeChatAiMomentsConfigView.tsx',
    kind: 'image',
    description: '探测图片生成接口是否可用。',
    content: '朋友圈图片能力探测',
    variables: [],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.characterSystem',
    moduleId: 'social-bonds',
    title: '微信聊天：角色 System Prompt',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    description: '构造微信文字聊天、语音通话、转账判断等角色扮演 system prompt。',
    content: '你正在微信里扮演「${characterName}」和我聊天。\n人物简介：${description}\n性格与说话方式：${personality}\n开场语气参考：${greeting}\n\n回复原则：\n- 活人感优先：像真实微信好友临场反应，不像资料抽取器、任务助手、客服或设定朗读。\n- 先接情绪和语境，再决定要不要给信息；可以轻松、犹豫、吐槽、敷衍半句、顺着玩笑走。\n- 文字微信优先只输出 1 句；语音通话要更短、更即时。\n- 如果要表达表情，只能使用默认表情短码：[冷笑]、[流泪]、[大哭]、[大笑]、[发怒]、[酷]、[爱心]、[点赞]、[害羞]、[震惊]、[睡觉]、[眨眼]、[生病]、[不要]、[便便]、[庆祝]，界面会渲染成表情图片；不要输出“[动画表情]”“[奸笑]”这类不存在的表情文字。\n${extraInstruction}',
    variables: ['characterName', 'description', 'personality', 'greeting', 'extraInstruction'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.context.worldBook',
    moduleId: 'social-bonds',
    title: '微信聊天：世界书上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '以下是低优先级世界书片段，只能在和当前最后一轮消息直接相关时辅助理解设定；不要主动扩写片段里的旧事件：\n${relevantWorldBookLines}',
    description: '把世界书片段作为低优先级上下文注入。',
    variables: ['relevantWorldBookLines'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.context.memory',
    moduleId: 'social-bonds',
    title: '微信聊天：长期记忆上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '以下是极少量低优先级长期记忆，只能在和当前最后一轮消息强相关时辅助判断偏好；不要复述，不要主动拉回旧事件，不要为了使用记忆而改变当前话题：\n${memoryLines}',
    description: '把长期记忆作为低优先级上下文注入。',
    variables: ['memoryLines'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.context.personalProfile',
    moduleId: 'social-bonds',
    title: '微信聊天：个人信息上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '以下是用户在其他应用中沉淀的个人信息，请仅在相关时自然参考，不要生硬复述：\n${personalProfileLines}',
    description: '把个人信息作为上下文注入。',
    variables: ['personalProfileLines'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.context.sessionIntro',
    moduleId: 'social-bonds',
    title: '微信聊天：当前会话说明',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '下面是当前微信会话，请按时间顺序理解对话推进。上面的世界书、长期记忆和个人信息只用于背景、口吻、偏好参考，不要替代当前话题，也不要主动续写旧事件。',
    description: '当前会话上下文前置说明。',
    variables: [],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.context.latestTurn',
    moduleId: 'social-bonds',
    title: '微信聊天：最后一轮用户消息说明',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '请基于以上上下文自然承接最后一轮用户连续消息，而不是只看最后一句，也不要重新开启前面已经说过的话题。\n核对事实归属：用户消息只能证明用户说过/做过的事；角色消息只能证明你说过/做过的事。不要把你自己的邀约、请求或玩笑说成是用户提出的。\n最近角色已回复过的内容就在上方会话里；不要复用其中的梗、关键词或整句。用户如果在确认、拒绝、结束或收尾，就顺着收住，不要继续上一话题。\n最后一轮用户连续消息：\n${latestUserContent}',
    description: '最后一轮连续用户消息的处理规则。',
    variables: ['latestUserContent'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.specialMessage.image',
    moduleId: 'social-bonds',
    title: '微信聊天：图片转上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'vision',
    content: '${normalizedCaption}',
    description: '把图片消息转换成模型可理解的文本提示。',
    variables: ['normalizedCaption'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.specialMessage.order',
    moduleId: 'social-bonds',
    title: '微信聊天：订单转上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'template',
    content: '[系统记录：${actionText}；金额：¥${amount}${orderIdsText}${orderPreviewText}]',
    description: '把代付订单消息转换成 AI 上下文。',
    variables: ['actionText', 'amount', 'orderIdsText', 'orderPreviewText'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.specialMessage.movieTicket',
    moduleId: 'social-bonds',
    title: '微信聊天：电影票转上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'template',
    content: '[系统记录：分享了一张电影票；电影：${title}；影院：${cinema}；时间：${date} ${time}；影厅：${hall}；座位：${seat}；数量：${qty}张；取票码：${pickupCode}]',
    description: '把电影票卡片转换成 AI 上下文。',
    variables: ['title', 'cinema', 'date', 'time', 'hall', 'seat', 'qty', 'pickupCode'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.specialMessage.gift',
    moduleId: 'social-bonds',
    title: '微信聊天：礼物转上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'template',
    content: '[系统记录：收到一份礼物；名称：${productName}；金额：¥${amount}；订单号：${orderId}]',
    description: '把礼物卡片转换成 AI 上下文。',
    variables: ['productName', 'amount', 'orderId'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.specialMessage.recipe',
    moduleId: 'social-bonds',
    title: '微信聊天：菜谱转上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'template',
    content: '[系统记录：收到一张菜谱卡片；菜名：${title}；说明：${subtitle}；用时：${time}；份量：${servings}；食材：${ingredientText}]',
    description: '把菜谱卡片转换成 AI 上下文。',
    variables: ['title', 'subtitle', 'time', 'servings', 'ingredientText'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.specialMessage.listenInvite',
    moduleId: 'social-bonds',
    title: '微信聊天：一起听歌邀请转上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'template',
    content: '[系统记录：一起听歌邀请：${inviterName}邀请你加入一起听歌；状态：${statusText}${trackText}]',
    description: '把一起听歌邀请转换成 AI 上下文。',
    variables: ['inviterName', 'statusText', 'trackText'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.specialMessage.listenSummary',
    moduleId: 'social-bonds',
    title: '微信聊天：一起听歌记录转上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'template',
    content: '[系统记录：一起听歌记录：我们一起听了${durationText}]',
    description: '把一起听歌记录转换成 AI 上下文。',
    variables: ['durationText'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.specialMessage.transfer',
    moduleId: 'social-bonds',
    title: '微信聊天：转账转上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'template',
    content: '[系统记录：用户向你发起了转账 ¥${amount}]',
    description: '把转账消息转换成 AI 上下文。',
    variables: ['amount'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.specialMessage.transferAccepted',
    moduleId: 'social-bonds',
    title: '微信聊天：收款记录转上下文',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'template',
    content: '[系统记录：你已接收转账 ¥${amount}]',
    description: '把已收款消息转换成 AI 上下文。',
    variables: ['amount'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.orderRequestDecision',
    moduleId: 'social-bonds',
    title: '微信聊天：代付决策标签',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '代付订单规则：\n- 如果聊天上下文里出现待支付的代付订单，请结合最近聊天内容、熟悉程度、对话语气、对方是否经常找你帮忙、金额大小和当前语境，判断是否愿意代付。\n- 如果愿意代付，就在回复最前面输出 [ORDER_REQUEST:accepted]。\n- 如果不愿意代付，就在回复最前面输出 [ORDER_REQUEST:rejected]。\n- 尽量给出明确决定，不要只因为“信息不足”就回避；只有真的需要继续追问时才不要输出标签。\n- 标签后面继续正常聊天回复，不要解释标签本身。',
    description: '出现待处理代付订单时，要求角色明确接受或拒绝并通过标签驱动 UI 状态。',
    variables: [],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.listenTogetherDecision',
    moduleId: 'social-bonds',
    title: '微信聊天：一起听歌决策标签',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '一起听歌邀请规则：\n- 如果聊天上下文里出现“一起听歌/加入一起听”的邀请卡，请结合最近聊天内容、熟悉程度、对话语气、当前心情和人物关系，判断是否愿意加入。\n- 如果愿意加入，就在回复最前面输出 [LISTEN_TOGETHER:accepted]。\n- 如果不愿意加入，就在回复最前面输出 [LISTEN_TOGETHER:rejected]。\n- 标签后面继续正常聊天回复，不要解释标签本身。',
    description: '出现一起听歌邀请时，要求角色明确加入或拒绝并通过标签驱动 UI 状态。',
    variables: [],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.movieTicketDecision',
    moduleId: 'social-bonds',
    title: '微信聊天：电影票决策标签',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '电影票规则：\n- 如果聊天上下文里出现电影票卡片，请结合电影、影院、时间、座位、关系亲近度和当前语气，判断角色是否愿意去看或如何回应。\n- 如果愿意去或表现出接受，就在回复最前面输出 [MOVIE_TICKET:accepted]。\n- 如果不愿意去或明确拒绝，就在回复最前面输出 [MOVIE_TICKET:rejected]。\n- 如果需要改时间、问细节或暂不确定，就不要输出标签，直接自然追问或回应。\n- 标签后面继续正常聊天回复，不要解释标签本身。',
    description: '出现电影票卡片时，要求角色判断是否接受邀约或自然追问。',
    variables: [],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.giftDecision',
    moduleId: 'social-bonds',
    title: '微信聊天：礼物决策标签',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '礼物规则：\n- 如果聊天上下文里出现礼物卡片，请结合礼物内容、关系亲近度、角色性格和当前语气，判断角色是否接受、害羞感谢、拒绝或追问。\n- 如果愿意接受礼物，就在回复最前面输出 [GIFT:accepted]。\n- 如果不愿意接受或明确拒绝，就在回复最前面输出 [GIFT:rejected]。\n- 如果只是惊讶、确认收件信息或需要继续问，不要输出标签，直接自然回复。\n- 标签后面继续正常聊天回复，不要解释标签本身。',
    description: '出现礼物卡片时，要求角色判断是否接受礼物或自然回应。',
    variables: [],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.recipeDecision',
    moduleId: 'social-bonds',
    title: '微信聊天：菜谱决策标签',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '菜谱规则：\n- 如果聊天上下文里出现菜谱卡片，请结合菜名、食材、角色口味、关系语气和当前话题，判断角色是否想尝试、喜欢、拒绝或追问做法。\n- 如果愿意尝试或表示喜欢，就在回复最前面输出 [RECIPE_CARD:accepted]。\n- 如果不想吃、不适合或明确拒绝，就在回复最前面输出 [RECIPE_CARD:rejected]。\n- 如果只是评价、开玩笑或追问细节，不要输出标签，直接自然回复。\n- 标签后面继续正常聊天回复，不要解释标签本身。',
    description: '出现菜谱卡片时，要求角色判断是否想尝试或自然回应。',
    variables: [],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.imageDecision',
    moduleId: 'social-bonds',
    title: '微信聊天：图片决策标签',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '图片规则：\n- 如果聊天上下文里出现用户发送的图片，请优先基于图片内容和附言自然回应，不要只说“我看到了”。\n- 如果图片表达的是邀请、展示成果、求评价或求安慰，请结合角色关系给出明确态度。\n- 如果喜欢、认可或愿意回应图片里的邀约，就在回复最前面输出 [IMAGE_MESSAGE:accepted]。\n- 如果不喜欢、拒绝图片里的邀约或明确否定，就在回复最前面输出 [IMAGE_MESSAGE:rejected]。\n- 如果只是描述、追问或安慰，不要输出标签，直接自然回复。\n- 标签后面继续正常聊天回复，不要解释标签本身。',
    description: '出现图片消息时，要求角色基于图片内容做出明确或自然的回应。',
    variables: [],
  }),
  definePaperMagicPrompt({
    id: 'wechat.chat.transferDecision',
    moduleId: 'social-bonds',
    title: '微信聊天：转账接收判断',
    source: 'src/appsrc/apps/WeChat/components/WeChatChatView.tsx',
    kind: 'chat',
    content: '[系统紧急提示：用户刚刚向你发起了一笔转账，金额：¥${amount}。如果你选择接收这笔钱，请必须在回复中包含“【接收转账】”这四个字；如果不接收或想忽略，请正常回复其他内容即可。]',
    description: '用户发起转账时，要求角色决定是否接收。',
    variables: ['amount'],
  }),
  definePaperMagicPrompt({
    id: 'wechat.voice.ttsPayload',
    moduleId: 'social-bonds',
    title: '微信/设置：Minimax 语音合成',
    source: 'src/appsrc/apps/WeChat/voice/minimaxVoiceProvider.ts',
    kind: 'voice',
    description: '把回复文本或测试文本发送给 Minimax TTS。',
    content: '{"model":"${model}","text":"${text}","stream":false,"output_format":"hex","voice_setting":{"voice_id":"${voiceId}","speed":1,"vol":1,"pitch":0},"audio_setting":{"sample_rate":32000,"bitrate":128000,"format":"mp3","channel":1}}',
    variables: ['model', 'text', 'voiceId'],
  }),
];
