export const FONT_STACK = '"HarmonyOS Sans SC","SF Pro Display","PingFang SC","Microsoft YaHei",sans-serif';

export const LETTER_INDEX = ['#', ...Array.from({ length: 26 }, (_, i) => String.fromCharCode(65 + i))];

export const TEXT = {
  phone: '电话',
  contacts: '联系人',
  favorites: '收藏',
  searchPlaceholder: '搜索联系人',
  myCard: '我的名片',
  myCardDesc: '查看和分享个人名片',
  allCalls: '全部通话',
  missedCalls: '未接来电',
  voicemail: '语音信箱',
  noRecords: '暂无通话记录',
  noContacts: '暂无联系人',
  noFavorites: '暂无收藏联系人',
  addContact: '新增联系人',
  editContact: '编辑联系人',
  contactDetail: '联系人详情',
  save: '保存',
  cancel: '取消',
  back: '返回',
  edit: '编辑',
  clear: '清空',
  callRecords: '通话记录',
  defaultRingtone: '默认',
  ringtone: '电话铃声',
  mobileLabel: '手机',
  noContactRecords: '暂无此联系人的通话记录',
  seconds: '秒',
  moreOptions: '更多选项',
  unknownCaller: '未知来电',
  tapToCall: '点击可发起通话',
  name: '姓名',
  phoneNumber: '手机号',
  note: '备注',
  description: '描述',
  greeting: '开场白',
  gender: '性别',
  age: '年龄',
  height: '身高',
  weight: '体重',
  wechatId: '微信号',
  introduction: '详细介绍',
  myCardList: '我的名片',
  addMyCard: '添加名片',
  editMyCard: '编辑名片',
  noMyCards: '暂无名片，点击右上角添加',
  male: '男',
  female: '女',
  unknown: '未知',
  chooseWorldBook: '角色世界书',
  notSelected: '未选择',
  noWorldBook: '暂无世界书',
  setAvatar: '设置头像',
  ungrouped: '未分组',
};
