import type {
  DeliveryMenuCategory,
  DeliveryMenuProduct,
  DeliveryOrderRecord,
  DeliveryStore,
} from './types';

export const DELIVERY_STORAGE_KEY = 'delivery-app-state-v2';

export const DELIVERY_MERCHANT = {
  id: 'delivery-main',
  name: '外卖',
  subtitle: '热饭热菜，随点随到',
  heroText: '今晚想吃什么，就点什么。',
  rating: 4.9,
  monthlySales: 2860,
  distanceKm: 1.8,
  deliveryFee: 3,
  minOrderAmount: 20,
  avgDeliveryMinutes: 32,
  notice: '店铺已休息，以下为演示模式。',
  isOpen: false,
};

export const DELIVERY_CATEGORIES: DeliveryMenuCategory[] = [
  { id: 'kitchen', name: '私家厨房', icon: '🍲', accent: '#d97706' },
  { id: 'food', name: '美食类', icon: '🍜', accent: '#f97316' },
  { id: 'drink', name: '甜点饮品', icon: '🧋', accent: '#ec4899' },
  { id: 'fresh', name: '蔬菜水果', icon: '🍏', accent: '#22c55e' },
  { id: 'medicine', name: '看病买药', icon: '💊', accent: '#3b82f6' },
  { id: 'night', name: '夜宵', icon: '🌙', accent: '#8b5cf6' },
  { id: 'custom', name: '购物车', icon: '+', accent: '#111827' },
];

export interface PrivateKitchenRecipeIngredient {
  productId: string;
  name?: string;
  amount: string;
  qty: number;
  price: number;
}

export interface PrivateKitchenRecipe {
  id: string;
  name: string;
  subtitle: string;
  accent: string;
  time: string;
  servings: string;
  ingredients: PrivateKitchenRecipeIngredient[];
  steps: string[];
  shareText: string;
}

export const DELIVERY_STORES: DeliveryStore[] = [
  {
    id: 'store-kitchen',
    categoryId: 'kitchen',
    name: '私家厨房',
    icon: '🍲',
    accent: '#d97706',
    subtitle: '家常菜谱与食材清单',
    rating: 4.9,
    monthlySales: 0,
    distanceKm: 1,
    deliveryFee: 0,
    minOrderAmount: 0,
    avgDeliveryMinutes: 20,
    notice: '家里的味道，简单一点也很好。',
    isOpen: true,
    sections: [
      { id: 'recipe', name: '家常菜谱' },
    ],
  },
  {
    id: 'store-bistro',
    categoryId: 'food',
    name: '拾味小馆',
    icon: '🍱',
    accent: '#f59e0b',
    subtitle: '轻食盖饭，口味温柔',
    rating: 4.8,
    monthlySales: 1205,
    distanceKm: 1.2,
    deliveryFee: 3,
    minOrderAmount: 20,
    avgDeliveryMinutes: 28,
    notice: '午晚高峰建议提前下单。',
    isOpen: true,
    sections: [
      { id: 'hot', name: '招牌热食' },
      { id: 'rice', name: '米饭套餐' },
      { id: 'snack', name: '小吃加料' },
    ],
  },
  {
    id: 'store-grill',
    categoryId: 'food',
    name: '街角烧烤铺',
    icon: '🍢',
    accent: '#ef4444',
    subtitle: '夜宵顶配，香气很近',
    rating: 4.7,
    monthlySales: 968,
    distanceKm: 2.6,
    deliveryFee: 4,
    minOrderAmount: 25,
    avgDeliveryMinutes: 34,
    notice: '深夜单量较多，配送更稳。',
    isOpen: true,
    sections: [
      { id: 'skewer', name: '烤串' },
      { id: 'bbq', name: '烧烤主菜' },
      { id: 'drink', name: '搭配饮品' },
    ],
  },
  {
    id: 'store-coffee',
    categoryId: 'drink',
    name: '拿铁咖啡屋',
    icon: '☕',
    accent: '#8b5cf6',
    subtitle: '偏安静的咖啡馆氛围',
    rating: 4.9,
    monthlySales: 720,
    distanceKm: 1.1,
    deliveryFee: 2,
    minOrderAmount: 18,
    avgDeliveryMinutes: 24,
    notice: '冷萃和奶咖都很稳。',
    isOpen: true,
    sections: [
      { id: 'espresso', name: '精品咖啡' },
      { id: 'milk', name: '奶咖' },
      { id: 'dessert', name: '甜点' },
    ],
  },
  {
    id: 'store-tea',
    categoryId: 'drink',
    name: '奈雪果茶',
    icon: '🧋',
    accent: '#ec4899',
    subtitle: '清爽果茶，适合拍照',
    rating: 4.8,
    monthlySales: 1580,
    distanceKm: 1.6,
    deliveryFee: 3,
    minOrderAmount: 19,
    avgDeliveryMinutes: 29,
    notice: '少糖更好喝。',
    isOpen: true,
    sections: [
      { id: 'tea', name: '果茶' },
      { id: 'milk-tea', name: '奶茶' },
      { id: 'season', name: '季节限定' },
    ],
  },
  {
    id: 'store-fresh',
    categoryId: 'fresh',
    name: '果然新鲜',
    icon: '🥝',
    accent: '#22c55e',
    subtitle: '现切现配，清爽解腻',
    rating: 4.7,
    monthlySales: 640,
    distanceKm: 2.3,
    deliveryFee: 4,
    minOrderAmount: 15,
    avgDeliveryMinutes: 22,
    notice: '水果每日到货。',
    isOpen: true,
    sections: [
      { id: 'fruit', name: '水果拼盘' },
      { id: 'snack', name: '健康小食' },
    ],
  },
  {
    id: 'store-medicine',
    categoryId: 'medicine',
    name: '夜间药房',
    icon: '💊',
    accent: '#3b82f6',
    subtitle: '应急必备，快速送达',
    rating: 4.9,
    monthlySales: 410,
    distanceKm: 3.3,
    deliveryFee: 5,
    minOrderAmount: 0,
    avgDeliveryMinutes: 18,
    notice: '夜间营业，常备药物齐全。',
    isOpen: true,
    sections: [
      { id: 'first-aid', name: '急救用品' },
      { id: 'cold', name: '感冒发热' },
    ],
  },
  {
    id: 'store-night',
    categoryId: 'night',
    name: '深夜食堂',
    icon: '🌙',
    accent: '#8b5cf6',
    subtitle: '夜里饿了就来这里',
    rating: 4.8,
    monthlySales: 932,
    distanceKm: 2.1,
    deliveryFee: 4,
    minOrderAmount: 25,
    avgDeliveryMinutes: 31,
    notice: '深夜慢一点，但很稳。',
    isOpen: true,
    sections: [
      { id: 'hotpot', name: '热乎小锅' },
      { id: 'noodle', name: '面食' },
      { id: 'drink', name: '夜间饮品' },
    ],
  },
];

export const DELIVERY_PRODUCTS: DeliveryMenuProduct[] = [
  {
    id: 'p1',
    storeId: 'store-bistro',
    categoryId: 'food',
    sectionId: 'hot',
    name: '培根卷金针菇',
    price: 4,
    stock: 48,
    sales: 128,
    description: '一口一个，热气腾腾。',
    tag: '热销',
    status: '上架',
  },
  {
    id: 'p2',
    storeId: 'store-bistro',
    categoryId: 'food',
    sectionId: 'rice',
    name: '玉米小把串',
    price: 7,
    stock: 36,
    sales: 94,
    description: '轻食夜宵，口感清甜。',
    tag: '推荐',
    status: '上架',
  },
  {
    id: 'p3',
    storeId: 'store-bistro',
    categoryId: 'food',
    sectionId: 'snack',
    name: '土豆片',
    price: 2,
    stock: 80,
    sales: 210,
    description: '薄脆入味，越吃越香。',
    tag: '爆款',
    status: '上架',
  },
  {
    id: 'p4',
    storeId: 'store-bistro',
    categoryId: 'food',
    sectionId: 'hot',
    name: '韭菜',
    price: 2,
    stock: 60,
    sales: 86,
    description: '新鲜清爽，简单好吃。',
    tag: '时蔬',
    status: '上架',
  },
  {
    id: 'p5',
    storeId: 'store-grill',
    categoryId: 'food',
    sectionId: 'skewer',
    name: '烤鸡翅中',
    price: 16,
    stock: 30,
    sales: 105,
    description: '外酥里嫩，微辣上头。',
    tag: '爆香',
    status: '上架',
  },
  {
    id: 'p6',
    storeId: 'store-grill',
    categoryId: 'food',
    sectionId: 'bbq',
    name: '烤五花肉',
    price: 22,
    stock: 26,
    sales: 88,
    description: '油脂焦香，越吃越想点。',
    tag: '主推',
    status: '上架',
  },
  {
    id: 'p7',
    storeId: 'store-grill',
    categoryId: 'food',
    sectionId: 'drink',
    name: '冰镇汽水',
    price: 6,
    stock: 42,
    sales: 59,
    description: '冰爽解腻，配烤串刚刚好。',
    tag: '搭配',
    status: '上架',
  },
  {
    id: 'p8',
    storeId: 'store-coffee',
    categoryId: 'drink',
    sectionId: 'espresso',
    name: '拿铁咖啡',
    price: 18,
    stock: 42,
    sales: 176,
    description: '丝滑奶泡，香气很稳。',
    tag: '新品',
    status: '上架',
  },
  {
    id: 'p9',
    storeId: 'store-coffee',
    categoryId: 'drink',
    sectionId: 'milk',
    name: '生椰拿铁',
    price: 22,
    stock: 35,
    sales: 121,
    description: '椰香浓郁，咖啡党会喜欢。',
    tag: '咖啡',
    status: '上架',
  },
  {
    id: 'p10',
    storeId: 'store-coffee',
    categoryId: 'drink',
    sectionId: 'dessert',
    name: '巴斯克蛋糕',
    price: 26,
    stock: 18,
    sales: 54,
    description: '口感柔软，适合拍照。',
    tag: '甜点',
    status: '上架',
  },
  {
    id: 'p11',
    storeId: 'store-tea',
    categoryId: 'drink',
    sectionId: 'tea',
    name: '芝士奶盖茶',
    price: 18,
    stock: 42,
    sales: 176,
    description: '奶盖细腻，入口更顺。',
    tag: '新品',
    status: '上架',
  },
  {
    id: 'p12',
    storeId: 'store-tea',
    categoryId: 'drink',
    sectionId: 'milk-tea',
    name: '草莓果茶',
    price: 20,
    stock: 30,
    sales: 118,
    description: '果香清甜，颜色也很好看。',
    tag: '推荐',
    status: '上架',
  },
  {
    id: 'p13',
    storeId: 'store-fresh',
    categoryId: 'fresh',
    sectionId: 'fruit',
    name: '苹果拼盘',
    price: 12,
    stock: 29,
    sales: 88,
    description: '现切现配，清爽解腻。',
    tag: '健康',
    status: '上架',
  },
  {
    id: 'p14',
    storeId: 'store-fresh',
    categoryId: 'fresh',
    sectionId: 'snack',
    name: '蓝莓酸奶杯',
    price: 15,
    stock: 24,
    sales: 68,
    description: '轻盈酸甜，适合下午。',
    tag: '轻食',
    status: '上架',
  },
  {
    id: 'p15',
    storeId: 'store-medicine',
    categoryId: 'medicine',
    sectionId: 'first-aid',
    name: '退热贴',
    price: 9,
    stock: 64,
    sales: 52,
    description: '夜间急需，快速送达。',
    tag: '应急',
    status: '上架',
  },
  {
    id: 'p16',
    storeId: 'store-medicine',
    categoryId: 'medicine',
    sectionId: 'cold',
    name: '感冒药',
    price: 28,
    stock: 18,
    sales: 36,
    description: '常备药品，说明详见包装。',
    tag: '夜间',
    status: '上架',
  },
  {
    id: 'p17',
    storeId: 'store-night',
    categoryId: 'night',
    sectionId: 'hotpot',
    name: '关东煮拼盘',
    price: 28,
    stock: 24,
    sales: 74,
    description: '深夜暖胃，汤底醇厚。',
    tag: '夜宵',
    status: '上架',
  },
  {
    id: 'p18',
    storeId: 'store-night',
    categoryId: 'night',
    sectionId: 'noodle',
    name: '香辣鸡翅中',
    price: 16,
    stock: 21,
    sales: 67,
    description: '外酥里嫩，微辣上头。',
    tag: '加辣',
    status: '上架',
  },
  {
    id: 'p19',
    storeId: 'store-night',
    categoryId: 'night',
    sectionId: 'drink',
    name: '蜂蜜柠檬水',
    price: 9,
    stock: 26,
    sales: 40,
    description: '清爽解腻，适合收尾。',
    tag: '清爽',
    status: '上架',
  },
  {
    id: 'kitchen-tomato',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '西红柿',
    price: 3,
    stock: 99,
    sales: 0,
    description: '做家常菜很百搭。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-egg',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '鸡蛋',
    price: 4,
    stock: 99,
    sales: 0,
    description: '简单又耐吃。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-porkloin',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '猪里脊',
    price: 16,
    stock: 99,
    sales: 0,
    description: '适合糖醋做法。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-corn',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '玉米',
    price: 5,
    stock: 99,
    sales: 0,
    description: '清甜又家常。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-ribs',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '排骨',
    price: 24,
    stock: 99,
    sales: 0,
    description: '炖煮都合适。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-eggplant',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '茄子',
    price: 4,
    stock: 99,
    sales: 0,
    description: '做地三鲜必备。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-potato',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '土豆',
    price: 3,
    stock: 99,
    sales: 0,
    description: '地三鲜里最灵魂的一味。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-greenpepper',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '青椒',
    price: 4,
    stock: 99,
    sales: 0,
    description: '带一点清香。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-shrimp',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '小龙虾',
    price: 58,
    stock: 99,
    sales: 0,
    description: '蒜蓉口味更香。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-garlic',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '大蒜',
    price: 2,
    stock: 99,
    sales: 0,
    description: '蒜香核心。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-fish',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '鲫鱼',
    price: 18,
    stock: 99,
    sales: 0,
    description: '清蒸很鲜。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-scallion',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '葱姜',
    price: 2,
    stock: 99,
    sales: 0,
    description: '去腥提鲜。',
    tag: '食材',
    status: '上架',
  },
  {
    id: 'kitchen-fan',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '番茄酱',
    price: 6,
    stock: 99,
    sales: 0,
    description: '糖醋味道更稳。',
    tag: '调料',
    status: '上架',
  },
  {
    id: 'kitchen-sugar',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '白糖',
    price: 2,
    stock: 99,
    sales: 0,
    description: '家里常备。',
    tag: '调料',
    status: '上架',
  },
  {
    id: 'kitchen-vinegar',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '陈醋',
    price: 4,
    stock: 99,
    sales: 0,
    description: '糖醋味的灵魂。',
    tag: '调料',
    status: '上架',
  },
  {
    id: 'kitchen-ricewine',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '料酒',
    price: 4,
    stock: 99,
    sales: 0,
    description: '去腥提鲜。',
    tag: '调料',
    status: '上架',
  },
  {
    id: 'kitchen-noodle',
    storeId: 'store-kitchen',
    categoryId: 'kitchen',
    sectionId: 'recipe',
    name: '粉丝',
    price: 6,
    stock: 99,
    sales: 0,
    description: '蒜蓉配一口更满足。',
    tag: '配菜',
    status: '上架',
  },
];

export const PRIVATE_KITCHEN_RECIPES: PrivateKitchenRecipe[] = [
  {
    id: 'recipe-tomato-egg',
    name: '西红柿炒鸡蛋',
    subtitle: '简单、下饭、永远不会出错',
    accent: '#fb7185',
    time: '15 分钟',
    servings: '2 人份',
    ingredients: [
      { productId: 'kitchen-tomato', name: '西红柿', amount: '2 个', qty: 2, price: 3.5 },
      { productId: 'kitchen-egg', name: '鸡蛋', amount: '3 个', qty: 3, price: 1.2 },
      { productId: 'kitchen-scallion', name: '葱花', amount: '1 把', qty: 1, price: 0.8 },
    ],
    steps: ['番茄切块，鸡蛋打散', '先炒鸡蛋，再下番茄', '最后加一点盐和葱花'],
    shareText: '今天想吃西红柿炒鸡蛋，简单又下饭。',
  },
  {
    id: 'recipe-sweet-sour-pork',
    name: '糖醋里脊',
    subtitle: '酸甜开胃，孩子也爱吃',
    accent: '#f97316',
    time: '25 分钟',
    servings: '2-3 人份',
    ingredients: [
      { productId: 'kitchen-porkloin', name: '里脊肉', amount: '300g', qty: 300, price: 0.08 },
      { productId: 'kitchen-fan', name: '番茄酱', amount: '2 勺', qty: 2, price: 1.5 },
      { productId: 'kitchen-sugar', name: '白糖', amount: '1 勺', qty: 1, price: 0.6 },
      { productId: 'kitchen-vinegar', name: '香醋', amount: '1 勺', qty: 1, price: 0.7 },
    ],
    steps: ['里脊切条腌一下', '调糖醋汁', '炸熟后收汁翻炒'],
    shareText: '今天做糖醋里脊，酸甜一口很治愈。',
  },
  {
    id: 'recipe-corn-ribs',
    name: '玉米排骨',
    subtitle: '一锅炖出家的香味',
    accent: '#d97706',
    time: '45 分钟',
    servings: '3 人份',
    ingredients: [
      { productId: 'kitchen-ribs', name: '排骨', amount: '500g', qty: 500, price: 0.09 },
      { productId: 'kitchen-corn', name: '玉米', amount: '1 根', qty: 1, price: 3.2 },
      { productId: 'kitchen-scallion', name: '葱花', amount: '1 把', qty: 1, price: 0.8 },
    ],
    steps: ['排骨焯水', '加入玉米慢炖', '出锅前撒葱花'],
    shareText: '今晚来一锅玉米排骨，暖呼呼的。',
  },
  {
    id: 'recipe-di-san-xian',
    name: '地三鲜',
    subtitle: '茄子、土豆、青椒，经典家常味',
    accent: '#22c55e',
    time: '20 分钟',
    servings: '2 人份',
    ingredients: [
      { productId: 'kitchen-eggplant', name: '茄子', amount: '1 根', qty: 1, price: 2.8 },
      { productId: 'kitchen-potato', name: '土豆', amount: '1 个', qty: 1, price: 2.2 },
      { productId: 'kitchen-greenpepper', name: '青椒', amount: '1 个', qty: 1, price: 1.8 },
    ],
    steps: ['食材切块', '分别煎至表面微焦', '调味后快速翻炒'],
    shareText: '地三鲜最适合配米饭了。',
  },
  {
    id: 'recipe-garlic-lobster',
    name: '蒜蓉龙虾',
    subtitle: '蒜香浓郁，夜宵氛围拉满',
    accent: '#ef4444',
    time: '30 分钟',
    servings: '2 人份',
    ingredients: [
      { productId: 'kitchen-shrimp', name: '小龙虾', amount: '1 份', qty: 1, price: 28 },
      { productId: 'kitchen-garlic', name: '大蒜', amount: '1 头', qty: 1, price: 1.2 },
      { productId: 'kitchen-fan', name: '粉丝', amount: '1 把', qty: 1, price: 2.1 },
    ],
    steps: ['龙虾清洗处理', '蒜末爆香', '加粉丝一起焖煮'],
    shareText: '蒜蓉龙虾安排上，夜宵必须有它。',
  },
  {
    id: 'recipe-steamed-carp',
    name: '清蒸鲫鱼',
    subtitle: '做法简单，汤汁鲜甜',
    accent: '#38bdf8',
    time: '25 分钟',
    servings: '2 人份',
    ingredients: [
      { productId: 'kitchen-fish', name: '鲫鱼', amount: '1 条', qty: 1, price: 18 },
      { productId: 'kitchen-scallion', name: '葱花', amount: '1 把', qty: 1, price: 0.8 },
      { productId: 'kitchen-ricewine', name: '料酒', amount: '1 勺', qty: 1, price: 0.6 },
    ],
    steps: ['鲫鱼处理干净', '葱姜垫底去腥', '蒸熟后淋热油'],
    shareText: '清蒸鲫鱼，清爽又鲜美。',
  },
];

export const createSeedOrders = (): DeliveryOrderRecord[] => [
  {
    id: 'o1',
    type: '购买',
    title: '培根卷金针菇',
    merchantName: '拾味小馆',
    amount: 12,
    status: '已支付',
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
  },
  {
    id: 'o2',
    type: '发起代付',
    title: '芝士奶盖茶',
    merchantName: '奈雪果茶',
    amount: 18,
    status: '待支付',
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
  },
];
